#!/usr/bin/env ruby

require_relative '../lib/pocket_size/deploy'
require 'optparse'

@options = {
  dry_run: false,
  skip_deploy: false,
  skip_container: false,
  rebuild: false,
  force: false,
  dev_build_number: true
}

OptionParser.new do |opts|
  opts.on('--dry-run') do
    @options[:dry_run] = true
  end

  opts.on('--skip-container') do
    @options[:skip_container] = true
  end

  opts.on('--skip-deploy') do
    @options[:skip_deploy] = true
  end

  opts.on('--rebuild') do
    @options[:rebuild] = true
  end

  opts.on('--force') do
    @options[:force] = true
  end

  opts.on('--no-dev-build-number') do
    @options[:dev_build_number] = false
  end
end.parse!

command = ARGV.shift

case command
when 'deploy'
  config_path = ARGV.shift
  if config_path.nil?
    abort 'Missing configuration path as second argument. Usage: pocket-size-deploy deploy ./path/to/deploy/config.yml'
  end
  PocketSize::Deploy::Deployment.deploy!(config_path, **@options)
else
  abort "Unknown command: #{command}"
end
